---
title: "Introduction to R Studio"
author: "Steve Pederson"
date: "1 May, 2017"
output: 
  ioslides_presentation: 
    css: default.css
    fig_caption: yes
    keep_md: yes
    widescreen: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, 
											eval = FALSE, results ="hide",
											message = FALSE, warning = FALSE)
```

# Session 1 | Introduction to RStudio

## What is RStudio?

* `R` and `RStudio` are two separate but connected things
    + `R` is like the engine of your car
    + `RStudio` is the 'cabin' we use to interact with the engine
    + `RStudio` even comes with extra flashy features not related to `R` 
* `R` does all the calculations, manages the data, generates plots
* `RStudio` helps manage our code, displays the plots plus more

## What is RStudio | Extra Flashy Features

* Some very helpful features of `RStudio`
		+ We can write scripts and **execute code** interactively
    + Auto-completion by hitting the **\<tab\>** key
    + Use of `R Projects` to manage code/data for each project/analysis
    + We can see **everything** we need (directories, plots, code, history etc)
    + Integration with markdown, $\LaTeX$, bash, python, C++, version control software etc.

## Getting Started | Before we start

1. Create a folder on your computer for today's material
    + We recommend `Documents/R-Training-20170501` in your home folder
2. Go to https://uofabioinformaticshub.github.io/Roseworthy-R-20170501/
    + Download the data file `toothData.csv` into `Documents/R-Training-20170501`
3. Now we can open `RStudio`